Repository ashutoshkrris/EazyLoader, pull requests merged in 2021-10, with the labels that each got.

#14 Fetch contributors' details
  core/contributors.py
Labels: PR:Ready-to-Review

#47 Faq jaswanthreddypadala
  core/templates/index.html
Labels: PR:Ready-to-Review, kind/feature, size/L

#48 fixed issue #35
  Procfile
  core/__init__.py
  core/routes.py
  core/templates/youtube/single/download.html
  core/utils/yt_downloader.py
  main.py
  requirements.txt
Labels: PR:Ready-to-Review, size/L, kind/bug
